name: 'Build Debian Package'
description: 'Build HALPI2 daemon .deb package'

runs:
  using: 'composite'
  steps:
    - name: Build package
      run: ./run build
      shell: bash

    - name: List built packages
      run: ls -lh *.deb
      shell: bash
