name: 'Run Tests'
description: 'Run Python tests for HALPI2 daemon'

runs:
  using: 'composite'
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install uv
      uses: astral-sh/setup-uv@v4

    - name: Run tests
      run: uv run pytest
      shell: bash
