name: Release Drafter

on:
  push:
    # branches to consider in the event; optional, defaults to all
    branches:
      - main

jobs:
  update_release_draft:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Read version from VERSION file
        id: version
        run: |
          VERSION=$(cat VERSION | tr -d '\n\r ')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Found version: $VERSION"

      # Download packages built by the build workflow
      - name: Download packages from build workflow
        uses: actions/download-artifact@v4
        with:
          name: debian-packages-${{ steps.version.outputs.version }}
          path: packages/

      - name: List downloaded packages
        run: |
          echo "Downloaded packages:"
          ls -la packages/
          ls -1 packages/*.deb 2>/dev/null || echo "No packages found"

      # Drafts your next Release notes as Pull Requests are merged into "main"
      - uses: release-drafter/release-drafter@v6
        id: release_drafter
        with:
          version: ${{ steps.version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # Upload packages to the draft release
      - name: Upload packages to release
        if: steps.release_drafter.outputs.upload_url
        run: |
          for deb_file in packages/*.deb; do
            if [ -f "$deb_file" ]; then
              filename=$(basename "$deb_file")
              echo "Uploading $filename..."
              curl -H "Authorization: token $GITHUB_TOKEN" \
                   -H "Content-Type: application/vnd.debian.binary-package" \
                   --data-binary @"$deb_file" \
                   "${{ steps.release_drafter.outputs.upload_url }}?name=$filename"
            fi
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
